<?php 
//FILL WITH YOUR OAUTH CONSUMER KEY
define("CONSUMER_KEY", "YOUR-OAUTH-CONSUMER-KEY");

//FILL WITH YOUR OAUTH CONSUMER SECRET
define("CONSUMER_SECRET", "YOUR -AUTH-CONSUMER-SECRET");

//FILL WITH YOUR APPLICATION URL
define("SITE_URL_BASE", "YOUR-APPLICATION-URL");
?>